name: essen-messenger-bot
region: sgp
services:
- name: web
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: YOUR_GITHUB_USERNAME/essen-facebook-messenger
  build_command: npm install
  run_command: npm start
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PAGE_ACCESS_TOKEN
    type: SECRET
  - key: VERIFY_TOKEN
    type: SECRET
  - key: APP_SECRET
    type: SECRET
  - key: GEMINI_API_KEY
    type: SECRET
  - key: DB_PATH
    value: ./database/bot.db