name: essen-messenger-bot
region: sgp

# Main Bot Service
services:
- name: facebook-bot
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: singabyte/essen-facebook-messenger
  build_command: npm install
  run_command: npm start
  http_port: 3000
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /webhook
  envs:
  - key: NODE_ENV
    value: production
  - key: PAGE_ACCESS_TOKEN
    type: SECRET
  - key: VERIFY_TOKEN
    type: SECRET
  - key: APP_SECRET
    type: SECRET
  - key: GEMINI_API_KEY
    type: SECRET
  - key: DB_PATH
    value: /workspace/database/bot.db
  - key: PORT
    value: "3000"

# Admin Backend Service
- name: admin-api
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: singabyte/essen-facebook-messenger
  source_dir: /admin-interface/server
  build_command: npm install
  run_command: npm start
  http_port: 4000
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /api
  envs:
  - key: NODE_ENV
    value: production
  - key: JWT_SECRET
    type: SECRET
  - key: PORT
    value: "4000"
  - key: DB_PATH
    value: /workspace/database/bot.db
  - key: FRONTEND_URL
    value: ${APP_URL}

# Admin Frontend Static Site
static_sites:
- name: admin-ui
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: singabyte/essen-facebook-messenger
  source_dir: /admin-interface/client
  build_command: npm install && npm run build
  output_dir: dist
  routes:
  - path: /
  envs:
  - key: VITE_API_URL
    value: ${APP_URL}/api