name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          cd ~/essen-facebook-messenger
          git pull origin main
          npm install --production
          pm2 restart facebook-bot || pm2 start ecosystem.config.js
          pm2 save
          
    - name: Health check
      run: |
        sleep 10
        response=$(curl -s -o /dev/null -w "%{http_code}" https://${{ secrets.SERVER_HOST }}/health)
        if [ $response -ne 200 ]; then
          echo "Health check failed"
          exit 1
        fi
        echo "Deployment successful!"